### ISSUE TITLE
Doesn`t work on oracle VM (ubuntu)

### ISSUE THREAD

**Issue by 9241304** [AlexVlan/OpenVPN#1]
Seems, some installation steps are missing. Script can`t be used for now

**Comment by AlexVlan** [comment]
I recently checked the scripts, can you give me more information?
- What script did you use?
- What operating system?
- What are your errors?

**Comment by 9241304** [comment]
1. Ubuntu20+...
2.  Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1027-oracle x86_64), Oracle free tier
3. Errors related to CA, when script tried to register user. 
I took the same script from https://github.com/angristan/openvpn-install (interface looks like yours) with fix described in https://github.com/angristan/openvpn-install/issues/781 . So, all works for now. You can check that script

**Comment by AlexVlan** [comment]
Thanks, I'll check it
